version: '3'
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "80:80"
